import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportQuizResultPDF = ({ quiz, results }) => {
  const doc = new jsPDF();

  /* Title */
  doc.setFontSize(18);
  doc.text(quiz.title || "Quiz Result", 14, 20);

  /* Meta info */
  doc.setFontSize(11);
  doc.text(`Score: ${quiz.score}%`, 14, 30);
  doc.text(`Total Questions: ${results.length}`, 14, 36);
  doc.text(
    `Date: ${new Date(quiz.completedAt).toLocaleDateString()}`,
    14,
    42
  );

  /* Table data */
  const tableData = results.map((r, index) => [
    index + 1,
    r.question,
    r.selectedAnswer || "—",
    r.correctAnswer,
    r.isCorrect ? "Correct" : "Incorrect",
  ]);

  autoTable(doc, {
    startY: 50,
    head: [["#", "Question", "Your Answer", "Correct Answer", "Result"]],
    body: tableData,
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [79, 70, 229], // Indigo
    },
    alternateRowStyles: {
      fillColor: [245, 247, 255],
    },
  });

  


  /* Footer */
  doc.setFontSize(9);
  doc.text(
    "Generated by AI Learning Assistant",
    14,
    doc.internal.pageSize.height - 10
  );

  doc.save(`${quiz.title || "quiz-result"}.pdf`);
};
